# Generated by Django 2.2.4 on 2019-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_transaction_transactionleg'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='accounts',
            field=models.ManyToManyField(related_name='transactions', to='finances.Account'),
        ),
    ]
