# Generated by Django 2.2.4 on 2019-08-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False, verbose_name='appliance uuid')),
                ('name', models.CharField(max_length=255, verbose_name='appliance name')),
            ],
        ),
    ]
