# Generated by Django 2.2.4 on 2019-08-10 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='appliance name'),
        ),
        migrations.CreateModel(
            name='ApplianceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='link key')),
                ('dst_appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_links', to='appliances.Appliance')),
                ('src_appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_links', to='appliances.Appliance')),
            ],
        ),
    ]
