# Generated by Django 2.2.4 on 2019-08-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0003_auto_20190810_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='last_connected_at',
            field=models.DateTimeField(null=True, verbose_name='last connected at'),
        ),
    ]
