# Generated by Django 2.2.4 on 2019-08-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0004_appliance_last_connected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='consumer',
            field=models.CharField(default='chezbob.bobolith.apps.appliances.consumers.DummyConsumer', max_length=255, verbose_name='consumer class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliance',
            name='last_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last connected at'),
        ),
    ]
