# Generated by Django 2.2.4 on 2019-08-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliances', '0005_auto_20190811_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='last_heartbeart_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last heartbeat at'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='status',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('DOWN', 'Unresponsive')], default='DOWN', max_length=15),
        ),
    ]
